### ISSUE TITLE
MorningStar cannot find the ticker symbol you entered or it is INVALID

### ISSUE THREAD

**Issue by ethanopp** [petercerno/good-morning#21]
```
kr = gm.KeyRatiosDownloader()
kr_frames = kr.download('AAPL')
print(kr_frames)
```
returns

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\OPPENE\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\182.3911.33\helpers\pydev\_pydev_bundle\pydev_umd.py", line 194, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\OPPENE\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\182.3911.33\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/OPPENE/PyCharm/Projects/FinanceValuation/pullData.py", line 115, in <module>
    kr_frames = kr.download('AAPL')
  File "C:\Users\OPPENE\PyCharm\Projects\FinanceValuation\good_morning\good_morning.py", line 91, in download
    raise ValueError("MorningStar cannot find the ticker symbol "
ValueError: MorningStar cannot find the ticker symbol you entered or it is INVALID. Please try again.
```

**Comment by ethanopp** [comment]
Resolved once the following is merged...
https://github.com/petercerno/good-morning/pull/20/commits/9847b7767b9b8b1b5f439de842f4976956a0bec0
